### ISSUE TITLE
问下你natjs还在用吗？

### ISSUE THREAD

**Issue by yuan-gao** [501956430/weexxiami#1]
问下你natjs还在用吗？网上完全找不到资料😂

**Comment by 501956430** [comment]
你指的是nat-camera吧？  
nat-camera已经集成OK 了，拍照，拍摄视频可以，不过缺少很多功能，所以我现在转用RxGalleryFinal

**Comment by yuan-gao** [comment]
对啊   nat-camera  iOS 我可以用了  但是 andriod 调不起来相机  
QQ 交流吧 😄  576694369

**Comment by 501956430** [comment]
close
